---
title: "CP6"
author: "Justin Kaiser"
date: "2023-02-06"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
n = 1000 # pay attention to n here
set.seed(1)
x <- sort(runif(n)*2*pi)
y <- sin(x) + rnorm(n)/4
df <- data.frame(y, x)
plot(x, y, col = "gray")

# Estimation with degree = 2 (locally quadratic)

loe1 <- loess(y ~ x, degree = 2, span = 0.5)
yhat1 <- predict(loe1, x)
plot(x, y, col = "gray")
lines(x, yhat1, col = "red", lwd = 2)

## SHUFFLE
n <- nrow(df)
ind <- sample(n,n)
df1 <- df[ind,]

# slice to 10 peices
k <- 10
nslice <- floor(n/k)
val <- df1[1:nslice,]
train <- df1[-(1:nslice),]

# train loess span = 0.02 0.2, 1 
fit1 <- loess(y ~ x, 
              degree = 2, 
              span = 0.02, 
              data = train, 
              control = loess.control(surface = "direct"))
yhat1 <- predict(fit1,val$x)
sqrt(mean((yhat1 - y))^2)


fit2 <- loess(y ~ x, 
              degree = 2, 
              span = 0.2, 
              data = train, 
              control = loess.control(surface = "direct"))
yhat2 <- predict(fit2,val$x)
sqrt(mean((yhat2 - y))^2)

fit3 <- loess(y ~ x, 
              degree = 2, 
              span = 1, 
              data = train, 
              control = loess.control(surface = "direct"))
yhat3 <- predict(fit3,val$x)
sqrt(mean((yhat3 - y))^2)

#better way
best = 1;
for (i in 1:100) {
  fitGood <- loess(y ~ x, 
              degree = 2, 
              span = 0.1*i, 
              data = train, 
              control = loess.control(surface = "direct"))
  yhatGood <- predict(fitGood,val$x)
  curr <- sqrt(mean((yhatGood - y))^2)
  print(curr)
  if(curr < best){
    #print(best)
    print("is worst than")
    #print(curr)
    best = curr
  }
}
print(best)


```